# Generated by Django 4.2.10 on 2024-02-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='img',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
